-- Modular tier rename: STARTER→ESSENTIALS, GROWTH→PROFESSIONAL, PROFESSIONAL→BUSINESS, +PLATINUM
-- Order matters: free the PROFESSIONAL label before reusing it.

ALTER TYPE "SubscriptionTier" RENAME VALUE 'PROFESSIONAL' TO 'BUSINESS';
ALTER TYPE "SubscriptionTier" RENAME VALUE 'GROWTH' TO 'PROFESSIONAL';
ALTER TYPE "SubscriptionTier" RENAME VALUE 'STARTER' TO 'ESSENTIALS';
ALTER TYPE "SubscriptionTier" ADD VALUE 'PLATINUM' BEFORE 'ENTERPRISE';
