// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";
import { resolveMigrationDatabaseUrl } from "./src/lib/db/migration-database-url";

const repoRoot = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(repoRoot, ".env.local") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveMigrationDatabaseUrl(),
  },
});
