/**
 * README.md content for the data-export bundle (E2 / BRD §5.3).
 *
 * Pure function — pure formatting, no I/O. The composer in bundle.ts calls
 * this once after row counts are known and writes the result as
 * `README.md` at the root of the ZIP.
 */

import {
  EXPORT_SCHEMA_VERSION,
  type ExportMetadata,
  type RowCounts,
} from "./types";

const FILE_DESCRIPTIONS: Record<string, string> = {
  "advisor.csv": "Tenant advisor profile (firm name, branding, S3 keys for the logo).",
  "advisor_subdomain.csv": "Custom subdomain configuration for the advisor.",
  "clients.csv": "Client User accounts assigned to this advisor (credentials omitted).",
  "client_profiles.csv": "Per-client demographic + contact info (PII present).",
  "subscriptions.csv": "Stripe subscription rows for the advisor and any client subscriptions.",
  "client_advisor_assignments.csv": "Hinge table linking clients to this advisor.",
  "invite_codes.csv": "Invite codes minted by this advisor.",
  "household_members.csv": "Household member records owned by clients.",
  "intake_interviews.csv": "Client intake interview rows (audio metadata only — see audioS3Key).",
  "intake_responses.csv": "Per-question intake responses including transcriptions.",
  "intake_approvals.csv": "Advisor approval/rejection records for intake submissions.",
  "assessments.csv": "Risk assessment instances per client.",
  "assessment_responses.csv": "Per-question assessment responses.",
  "pillar_scores.csv": "Per-pillar scoring results (low/medium/high/critical).",
  "document_requirements.csv": "Document checklists + S3 keys for fulfilled documents.",
  "advisor_notifications.csv": "In-app notifications for the advisor.",
  "governance_review_leads.csv": "Public lead-form submissions assigned to this advisor.",
  "notification_preferences.csv": "Per-user email notification preferences.",
  "audit_log.csv": "Heap-merged audit log across all 3 audit tables, scoped to this tenant.",
};

function formatRowCounts(counts: RowCounts): string {
  const entries = Object.entries(counts).sort(([a], [b]) => a.localeCompare(b));
  const max = entries.reduce((m, [k]) => Math.max(m, k.length), 0);
  return entries
    .map(([k, n]) => `  ${k.padEnd(max)}  ${String(n).padStart(8)}`)
    .join("\n");
}

export function renderReadme(metadata: ExportMetadata): string {
  const scopeBanner =
    metadata.scope === "tenant"
      ? `**Scope:** per-tenant (advisor: ${metadata.advisor?.email ?? "?"})`
      : `**Scope:** system-wide (${metadata.tenants?.length ?? 0} tenants)`;

  const fileIndex = Object.entries(metadata.rowCounts)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, count]) => {
      const path = `csv/${file}.csv`;
      const desc = FILE_DESCRIPTIONS[`${file}.csv`] ?? "(no description)";
      return `- \`${path}\` (${count} rows) — ${desc}`;
    })
    .join("\n");

  return `# Akili Risk — Data Export

This archive contains a structured dump of client and advisor data
generated by the Akili Risk admin Data Export feature.

## Source: BRD §5.3 (Data Ownership)

The Belvedere Risk Management BRD §5.3 establishes the data-ownership
contract that this export fulfills:

> The customer retains full ownership of all data; the developer has no
> rights to commercialize. Full data export capability and structured
> data portability (CSV/JSON) are mandatory.

(The BRD is written from Belvedere's perspective as the lead customer;
the same ownership commitment applies to every tenant on the Akili Risk
platform.)

This bundle fulfills the portability commitment — every Postgres row
belonging to the export scope below is included in CSV form (one file per
table) plus a single nested JSON (\`data.json\`) for consumers that prefer
hierarchy over relational joins.

## Bundle metadata

- **Schema version:** \`${EXPORT_SCHEMA_VERSION}\` (consumers should
  dispatch on this — bumped on any column add/remove)
- **Generated at:** ${metadata.generatedAt}
- ${scopeBanner}
${
  metadata.advisor
    ? `- **Advisor profile id:** ${metadata.advisor.advisorProfileId}\n- **Advisor user id:** ${metadata.advisor.userId}\n- **Firm:** ${metadata.advisor.firmName ?? "(unset)"}`
    : ""
}

## File index

\`\`\`
${formatRowCounts(metadata.rowCounts)}
\`\`\`

${fileIndex}

## Notes on contents

- **PII is RAW.** This export is the unredacted source. The audit log
  inside the bundle (\`csv/audit_log.csv\`) is the redacted view per
  round-7's audit infrastructure; everything else is verbatim.
- **Credentials are omitted.** \`clients.csv\` excludes \`password\`,
  \`mfaSecret\`, and \`mfaRecoveryCodes\` columns.
- **Binary blobs are NOT included.** \`intake_responses.csv\` and
  \`document_requirements.csv\` reference S3 keys (\`audioS3Key\`,
  \`fileKey\`); the actual audio/document files live in S3 and require a
  separate download path. Use the keys to fetch the underlying objects
  from the Akili Risk S3 bucket.
- **Audit log is heap-merged across three tables** (round-8 unified read
  view): the generic \`AuditLog\` plus the legacy \`SubscriptionAuditLog\`
  and \`AdvisorBrandingAuditLog\`. The id column is source-prefixed
  (\`gen:\` / \`sub:\` / \`brand:\`) so rows remain unique across sources.

## Re-import

Re-importing this bundle is **out of scope for v1**. The export is
documented as a one-way data dump for ownership / portability. If you
need a re-importable dump, file a feature request — the moving parts are
schema validation, ID conflict resolution, and FK reordering.

## Where to find the schema

The Prisma schema in source (\`prisma/schema.prisma\`) is the canonical
column reference. CSV column order matches the order defined in
\`src/lib/export/serializers/csv.ts\` (\`COLUMNS_BY_TABLE\`).
`;
}
